version: '3'

services:
  grafana:
    image: custom-prometheus-grafana:latest
    build:
      context: grafana
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/1860_rev32.json"
        #
  prometheus:
    image: custom-prometheus-prometheus:latest
    build:
      context: prometheus
    network_mode: "host"
